dist: trusty
language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
    - "target/node_modules"
    - ~/.npm
    - ~/.cache
before_script: ./bin/prepare-repo-to-test.sh
script: npm run test
